### ISSUE TITLE
less: command not found

### ISSUE THREAD

**Issue by HareBrayn** [nodef/extra-marked#2]
Seems it's missing a lib called "less":

`
root@befea4d8988d:/home/v2# marked README.md 
/bin/sh: 1: less: not found
node:child_process:915
    throw err;
    ^

Error: Command failed: "/usr/local/bin/node" "/usr/local/bin/marked" "README.md" -v | less -r
    at checkExecSyncError (node:child_process:841:11)
    at Object.execSync (node:child_process:912:15)
    at shell (/usr/local/lib/node_modules/extra-marked/index.js:119:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/extra-marked/index.js:121:27)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 22680,
  stdout: null,
  stderr: null
}
`

**Comment by wolfram77** [comment]
Please check if the issue is resolved. `less` is a program/command available in linux that is used to view contents of a file. If less is not present, such as on windows, it should display the entire output on the terminal now. Thanks for reporting.
